### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by omni6**

### CODE REVIEW

**Comment by omni6** [comment]
oh i see.... think i was too fast xD

**Comment by omni6** [comment]
yeah noticed this and wondered why my translation was changed... and to the wrong i have to point out. i have reverted it already. why this is happened?

**Comment by JenaPlinsky** [comment]
I do not know why it happens
I solved if I remember correctly eliminating that string
I occurs, I think because I've edited the file by kwrite while the correct way would be use the apposite app **lokalize**

**Comment by omni6** [comment]
you had the same issue in your translation? i use poedit. anyway now everything should be correct again :)

**Comment by omni6** [comment]
@audoban @psifidotos are you able to merge or must i reset? what to do?

**Comment by audoban** [comment]
@omni6  Please do a rebase in your branch and fix the conflicts, there were some changes with the translation strings a few hours ago,.

**Comment by omni6** [comment]
you sure there are conflicts? because i fixed it already after you commited the compatiblity plasma 5.8 thingy.

**Comment by omni6** [comment]
oh something went wrong dont pull!

**Pull request closed without merging**
