### PR TITLE
Hide settings in contexts where it interferes with normal workflow

### PR DESCRIPTION
**Pull request by rokups**
As title says. Also puts `Close` item at the bottom.

### CODE REVIEW

**Comment by psifidotos** [comment]
I suppose this is from #644, let me play with it and provide feedback

**Comment by rokups** [comment]
Yes it is. And it certainly [is not the best way](https://github.com/psifidotos/Latte-Dock/pull/668/files#diff-83aa05c2117fae9e45ffb9bbda0aa153R916) to do it, but i did not know any better.

**Comment by psifidotos** [comment]
@rokups I played with... I can accept only the half of it, moving the Close action at the very bottom because of its special characteristics but the rest must remain as it is... I have this ready in my system if you agree

**Comment by rokups** [comment]
Sure, thank you 👍

**Comment by psifidotos** [comment]
ok... I merged it in master...

**Pull request closed without merging**
