### PR TITLE
Add rpm spec file for Fedora

### PR DESCRIPTION
**Pull request by marcdeop**

### CODE REVIEW

**Comment by psifidotos** [comment]
Sorry we dont add spec files... only links with the pre-built package to publish in our pages

**Comment by psifidotos** [comment]
You can add also the install instructions in the Installation.md as other distros are doing...

**Comment by psifidotos** [comment]
Concerning the bug #86 which is distro specific for Fedora, have you taken it into account?

**Comment by audoban** [comment]
Hello marcdep, I'm porting the spec file of openSUSE for Fedora, I'll take your spec file as a reference.

**Pull request closed without merging**
