### PR TITLE
fixes and additions

### PR DESCRIPTION
**Pull request by omni6**

### CODE REVIEW

**Comment by audoban** [comment]
Please send only one commit for update de.po

**Comment by omni6** [comment]
ok

**Comment by omni6** [comment]
odd, used to work more with the git command in terminal. thought it wouldl be a more cleaner solution than copy n paste my changes from one repo in another...  yesterday i pulled your repo to have it in sync and now every commit what is made by you will now be commited again. will have to read wiki....

**Comment by omni6** [comment]
> every commit what is made by you will now be commited again
wrong i know... can i merge my commit together?

**Comment by omni6** [comment]
when you accepted the pull request i run `git reset --hard @{u}` should reset my repo to upstream. is all this neccescary? idk... perhaps i stay on the webgui...

**Pull request closed without merging**
