### PR TITLE
Update INSTALLATION.md

### PR DESCRIPTION
**Pull request by omni6**
give the arch people the locale_prefix ;)

### CODE REVIEW

**Comment by audoban** [comment]
I don't know, maybe is unnecessary.

@psifidotos Because we don't using the macro `ki18n_install` on our CMakeLists.txt

**Comment by psifidotos** [comment]
> @psifidotos Why we don't using the macro ki18n_install on our CMakeLists.txt?

because personally I didnt know it existed!! What is it doing??? 
Can we have correct locales installation for both openSUSE and Arch without the user even setting anything?

**Comment by psifidotos** [comment]
@audoban  I found it!!! I am trying to reimplement things around this!! I will upload a branch to test!!!
it doesnt install at kf5 but it looks like that it works in openSUSE also... I hope you will confirm it...

**Comment by audoban** [comment]
> Can we have correct locales installation for both openSUSE and Arch without the user even setting anything?

Yes, ki18n_install is the standard form for install locale files.

**Comment by psifidotos** [comment]
any ideas how to use intltool-merge with ki18n_install directory structure ?

**Comment by audoban** [comment]
> any ideas how to use intltool-merge with ki18n_install directory structure ?

But is necessary? normally I just use the macro. And a script for merge the po files.

**Comment by psifidotos** [comment]
> But is necessary? normally I just use the macro. And a script for merge the po files.

of course it is... it is the one tool merging translations and putting them in the desktop files of each component... Otherwise the desktop files wont have translations in them... it is the tool generating metadata.desktop.cmake files that contain the  translations, except if the kde provides an alternative I dont know

**Comment by audoban** [comment]
> of course it is... it is the one tool merging translations and putting them in the desktop files of each component... Otherwise the desktop files wont have translations in them...

We can stop using this tool, and simply write translation into desktop files.

**Comment by psifidotos** [comment]
> We can stop using this tool, and simply write translation into desktop files.

I dont find this feasible... We can not require from translators to open and edit correctly our metadata.desktop files...

I dont know how Plasma is achieving this, if we find a way I will agree in the transition, it already works in my system but a way should be found in order to update the translations for the desktop files automatic

**Comment by psifidotos** [comment]
@audoban , instead of doing this why dont we just set as
set(KF5_LOCALE_PREFIX "")

as it appears in openSUSE it works also correctly...

**Comment by audoban** [comment]
Ok but I'll see if I can simplify the generation of the...

**Comment by psifidotos** [comment]
> Ok but I'll see if I can simplify the generation of the...

upload them first for review to be sure that this is not broken... I removed the kf5 prefix by default for translations... You can also check the newlocales branch it contains the transition you mentioned but without a working inttool-merge

**Comment by omni6** [comment]
last tagged and latest master are now available from AUR:
                                    
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=latte+dock&outdated=&SB=n&SO=a&PP=50&do_Search=Go

build went fine, locale work...all as expected.

**Comment by psifidotos** [comment]
:+1:

**Pull request merged**
