### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by gorevoy-vladislav**
Update Russian translation for new version Latte Dock

[Successfully tested!]

### CODE REVIEW

**Comment by psifidotos** [comment]
just as a notice... There will be a very big update in translation strings the next weeks because of preparation for Latte v0.7

**Comment by gorevoy-vladislav** [comment]
Ok! Thanks!

пн, 24 Июл 2017, 23:14 Michail Vourlakos <notifications@github.com>:

**Comment by gorevoy-vladislav** [comment]
Please, notice me, when final strings will be ready and before v.0.7 will
be released. If you can.

Thanks!

пн, 24 июл. 2017 г. в 23:14, Michail Vourlakos <notifications@github.com>:

**Comment by psifidotos** [comment]
@gorevoy-vladislav I updated the translation strings (this is not final, there will be probably one more merge in 10 days but it is going to be small)... the changes are a lot in this one because the new Layouts mechanism is supprted now!! different layouts per Activities... etc...

**Pull request merged**
