### PR TITLE
INSTALLATION.md

### PR DESCRIPTION
**Pull request by leosegovia**
Added missing libs to fix issues listed on post #203 #220 and #225

### CODE REVIEW

**Comment by psifidotos** [comment]
It isnt clean... you must rebase again to master...

**Comment by psifidotos** [comment]
I would commit from my account but I would prefer to be commited by you... 
please rebase this in order to accept your commit and merge it correctly...

**Comment by leosegovia** [comment]
I will as soon as I'm off class

**Comment by leosegovia** [comment]
I tried rebasing but I don't know if that is good now.... First time doing this O__o

**Comment by psifidotos** [comment]
it didnt :) dont worry....

you can do the following... close this pull request and try again from scratch...

**Pull request closed without merging**
