### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by BlackDragonDev**
Update polish translation

### CODE REVIEW

**Comment by BlackDragonDev** [comment]
It was. It's based on previous translation.

**Comment by psifidotos** [comment]
Sorry but we accept translations only produced by klokalize...

Hand made translations may break the install process

**Comment by BlackDragonDev** [comment]
Allright. Thank You for answer.

**Comment by audoban** [comment]
@BlackDragonDev thanks for you patience

**Comment by BlackDragonDev** [comment]
Allright, thank You very much for answer.

**Pull request closed without merging**
