### PR TITLE
German Translations

### PR DESCRIPTION
**Pull request by omni6**
found time to make a german translation. First time i made this, if anything isnt right please contact me.

Jan

### CODE REVIEW

**Comment by psifidotos** [comment]
Is it working ok in German in your system?

**Comment by omni6** [comment]
mhh i dont get it work in german, everthing appears still in english... :(

at compile 

```
-- Install configuration: "Release"
-- Installing: /usr/share/locale/kf5/de/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/de/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/zh_TW/LC_MESSAGES/latte-dock.mo

```
plasma locale are set to german, have i forgotten something?

**Comment by psifidotos** [comment]
it may not be **de**. Find the translation for an app that is shown in German, e.g. plasmashell,
in my system for greek that is:
/usr/share/locale/kf5/el/LC_MESSAGES/plasmashell.mo

can you find yours?

**Comment by omni6** [comment]
my locales are in 
`/usr/share/locale/de/LC_MESSAGES`

Archlinux!?

**Comment by omni6** [comment]
i think i need a compiler flag... 
KDE_INSTALL_LOCALEDIR

**Comment by psifidotos** [comment]
in Arch the plasma translations arent located at
/usr/share/locale/kf5?

I need feedback for this....

@audoban have you any idea for this?

**Comment by psifidotos** [comment]
@omni6 I have sent an e-mail to plasma-devel mailing list concerning this, in order to respond me what is the default behavior... Where the translations should be installed for plasma and where KDE_INSTALL_LOCALEDIR should point

**Comment by omni6** [comment]
hey symlinked /usr/share/locale/kf5/de/LC_MESSAGES/ to /usr/share/locale/kf5/de/LC_MESSAGES/

it works! will look for my translation now. i think the arch people will write the fitting pkgbuild for this. im not skilled enough to write pkgbuilds...

**Comment by omni6** [comment]
i think you can merge, looks all very fine.

**Comment by psifidotos** [comment]
ok, I merged it...
In latest master I have added also an easy way to fix the KF5 locale directory...
You can access the main CMakeList.txt and change:

`set(KF5_LOCALE_PREFIX "kf5/")`

to : 

`set(KF5_LOCALE_PREFIX "")`

**Comment by omni6** [comment]
great!

**Pull request merged**
