### PR TITLE
Add development packages you need to install on README

### PR DESCRIPTION
**Pull request by mateushonorato**
Just added the packages needed to install, so it will be easier to a newbie user to install.

### CODE REVIEW

**Comment by audoban** [comment]
But we have wait to @psifidotos for his opinion.

**Comment by psifidotos** [comment]
It's a good idea

but plasma-desktop-dev I dont think it is needed... we use plasma-workspace-dev for the libtaskmanager but i cant think of any need for plasma-desktop-dev

**Comment by psifidotos** [comment]
Thinking it second time neither workspace-dev is needed... our build need only kde frameworks ... the libtaskmanager is used only in qml part... @audoban have you thought that Latte might works just fine also in other desktop environments as long as kde frameworks is installed?

**Comment by audoban** [comment]
> have you thought that Latte might works just fine also in other desktop environments as long as kde frameworks is installed?

Maybe, but we need testing with others desktops and Windows Managers.

**Comment by psifidotos** [comment]
> Maybe, but we need testing with others desktops and Windows Managers

of course.... this is not even a priority, I just pointed out the interest in such a case...

concerning this patch, i have the opinion that it must be updated to what our cmake files point out as requirements. After that no prob at all, we merge it directly...

**Comment by psifidotos** [comment]
Needed from KDE Frameworks based on openSUSE:

plasma-framework-devel
ki18n-devel
kcoreaddons-devel
kxmlgui-devel
kactivities5-devel
kdeclarative-devel
kwindowsystem-devel
kiconthemes-devel

for qt and x11 I think @audoban is better to specify what -devel packages are needed...

Also there are cases that no -devel is needed but specific lib does (qml cases)...

When the project reaches a point in which we are talking for a release I will create a .spec for openSUSE Build Service, from there it will be pretty obvious what is needed to compile and what is needed to be built properly...

**Comment by audoban** [comment]
for qt I think latte need libQt5Core-devel and libqt5-qtx11extras-devel
KF5KDELibs4Support, It is no longer necessary.
The dependencies for QtQuick should be satisfied by default on a Plasma desktop.

> When the project reaches a point in which we are talking for a release I will create a .spec for openSUSE Build Service, from there it will be pretty obvious what is needed to compile and what is needed to be built properly...

of course, OBS is the best tool for create packages for any distribution.

**Comment by Saboteur777** [comment]
https://github.com/psifidotos/Latte-Dock/pull/64
https://github.com/psifidotos/Latte-Dock/pull/69

**Comment by audoban** [comment]
The README has been updated.

**Pull request closed without merging**
