### PR TITLE
Update It translation

### PR DESCRIPTION
**Pull request by JenaPlinsky**

### CODE REVIEW

**Comment by audoban** [comment]
this PR has a duplicate commit https://github.com/psifidotos/Latte-Dock/pull/321/commits/58573de996d1a9c9df7cea0c33be3621de82dbff

**Comment by audoban** [comment]
tell me e0604e4175589a35784ff76985c8b3d76050f049 and https://github.com/psifidotos/Latte-Dock/pull/321/commits/58573de996d1a9c9df7cea0c33be3621de82dbff are exactly equals?

**Comment by JenaPlinsky** [comment]
Yes

I'm just adding files
step1 po/app
step2  po/containment
step3 po/plasmoid

in PR git me also proposes the previous files
I have not made changes to the previous files

**Comment by audoban** [comment]
@JenaPlinsky Do you have any other changes for your language?

**Comment by JenaPlinsky** [comment]
for the moment no ...esso puo andare così

then I will make an installation from the master branch to check all

**Comment by audoban** [comment]
your master branch builds correctly. 👍

**Pull request merged**
