### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by JenaPlinsky**

### CODE REVIEW

**Comment by psifidotos** [comment]
Does this fix the issue with italian translation?

**Comment by JenaPlinsky** [comment]
if you make me upload, I confirm immediately

**Comment by psifidotos** [comment]
you can confirm it without uploading in master... make your changes and run sh install.sh... close Latte and open it... has the issue fixed?

**Comment by JenaPlinsky** [comment]
2 minutes and I can tell you
I noticed that also audouban has the same type of problem

**Comment by JenaPlinsky** [comment]
@psifidotos yes it is fixed
by deleting tag "fuzy"
...i can't find new string on the tweaks

**Comment by psifidotos** [comment]
Nice!!!  Strings for Tweaks page havent been published yet...

**Pull request merged**
