### PR TITLE
Update and add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I update and add some zh_TW translations, please review and merge it 😄 
And I want to ask if Now Dock will continue to maintain or drop?

### CODE REVIEW

**Comment by audoban** [comment]
Latte Dock is the union between now dock and candil dock, then probably nop.

**Comment by audoban** [comment]
Latte Dock is the union between now dock and candil dock, then probably nop.

**Comment by audoban** [comment]
With respect to commit, Keep in mind that today there will be changes in the strings.

**Comment by s8321414** [comment]
\o/

**Pull request merged**
